import React from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import {
  FaLeaf,
  FaCheckCircle,
  FaExclamationTriangle,
  FaArrowLeft,
  FaDownload,
  FaShareAlt
} from 'react-icons/fa';
import { motion } from 'framer-motion';

const PredictionResult = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const prediction = location.state;

  if (!prediction) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-green-50 via-emerald-50 to-white px-4">
        <div className="bg-white rounded-3xl shadow-lg p-8 text-center max-w-md">

          <FaLeaf className="text-5xl text-green-500 mx-auto mb-4" />

          <h2 className="text-2xl font-bold text-gray-800 mb-2">
            No Prediction Found
          </h2>

          <p className="text-gray-500 mb-6">
            Please upload a plant leaf image first.
          </p>

          <Link
            to="/detection"
            className="inline-block px-6 py-3 bg-green-500 text-white rounded-xl font-semibold hover:bg-green-600 transition-all"
          >
            Start Detection
          </Link>

        </div>
      </div>
    );
  }

  const isLeaf = prediction.is_leaf !== false;

  const disease = prediction.disease || 'Unknown';

  const confidence = Number(
    prediction.confidence || 0
  );

  const preview = prediction.preview;

  const filename =
    prediction.filename || 'Uploaded Image';

  const message =
    prediction.message ||
    'Please upload a plant leaf image.';

  const isHealthy =
    disease.toLowerCase().includes('healthy');

  const status = isHealthy
    ? 'Healthy'
    : 'Diseased';

  const formatDiseaseName = (name) => {
    return name
      .replace(/___/g, ' - ')
      .replace(/_/g, ' ');
  };

  const formattedDisease =
    formatDiseaseName(disease);

  const plantName = disease.includes('___')
    ? disease
        .split('___')[0]
        .replace(/_/g, ' ')
    : 'Plant';

  const handleShare = async () => {

    const shareText = isLeaf
      ? `DeepLeaf Prediction: ${formattedDisease} (${confidence.toFixed(2)}% confidence)`
      : `DeepLeaf: ${message}`;

    try {

      if (navigator.share) {

        await navigator.share({
          title: 'DeepLeaf Prediction',
          text: shareText
        });

      } else {

        await navigator.clipboard.writeText(
          shareText
        );

        alert(
          'Prediction copied to clipboard!'
        );

      }

    } catch (error) {
      console.log('Share cancelled');
    }
  };

  const handleDownload = () => {

    const resultText = isLeaf
      ? `
DeepLeaf AI - Plant Disease Detection

Image: ${filename}
Plant: ${plantName}
Disease: ${formattedDisease}
Status: ${status}
Confidence: ${confidence.toFixed(2)}%

Generated by DeepLeaf AI
      `.trim()
      : `
DeepLeaf AI - Plant Disease Detection

Image: ${filename}
Status: Not a Leaf
Message: ${message}

Generated by DeepLeaf AI
      `.trim();

    const blob = new Blob(
      [resultText],
      { type: 'text/plain' }
    );

    const url =
      URL.createObjectURL(blob);

    const link =
      document.createElement('a');

    link.href = url;

    link.download =
      'deepleaf-prediction.txt';

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  if (!isLeaf) {

    return (
      <div className="min-h-screen py-12 bg-gradient-to-br from-green-50 via-emerald-50 to-white">

        <div className="container mx-auto px-4">

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto"
          >

            <div className="flex items-center justify-between mb-6">

              <button
                onClick={() =>
                  navigate('/detection')
                }
                className="flex items-center space-x-2 text-green-600 hover:text-green-700"
              >
                <FaArrowLeft />

                <span>
                  Back
                </span>

              </button>

              <div className="flex items-center space-x-3">

                <button
                  onClick={handleShare}
                  className="p-2 text-gray-500 hover:text-green-600 transition-colors"
                  title="Share"
                >
                  <FaShareAlt />
                </button>

                <button
                  onClick={handleDownload}
                  className="p-2 text-gray-500 hover:text-green-600 transition-colors"
                  title="Download"
                >
                  <FaDownload />
                </button>

              </div>

            </div>

            <div className="bg-white rounded-3xl shadow-lg overflow-hidden">

              <div className="bg-gradient-to-r from-green-500 to-emerald-600 p-8 text-white">

                <h1 className="text-3xl font-bold">
                  Image Result
                </h1>

                <p className="text-green-100 mt-1">
                  Image analysis completed
                </p>

              </div>

              <div className="p-8">

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">

                  <div>

                    {preview ? (

                      <div className="bg-gray-50 rounded-2xl p-4">

                        <img
                          src={preview}
                          alt="Uploaded image"
                          className="w-full max-h-80 object-contain rounded-xl"
                        />

                        <p className="text-xs text-gray-500 text-center mt-3 break-all">
                          {filename}
                        </p>

                      </div>

                    ) : (

                      <div className="bg-green-50 rounded-2xl p-8 flex items-center justify-center">
                        <FaLeaf className="text-7xl text-green-500" />
                      </div>

                    )}

                  </div>

                  <div className="flex flex-col justify-center">

                    <div className="inline-flex items-center w-fit px-4 py-2 rounded-xl font-semibold bg-red-100 text-red-600 mb-5">

                      <FaExclamationTriangle className="mr-2" />

                      Not a Leaf

                    </div>

                    <h2 className="text-2xl font-bold text-gray-900 mb-3">
                      Plant Leaf Required
                    </h2>

                    <p className="text-gray-600 text-lg mb-6">
                      {message}
                    </p>

                    <div className="bg-yellow-50 border border-yellow-200 rounded-2xl p-5 mb-6">

                      <p className="text-yellow-800">
                        Disease detection is available only for plant leaf images.
                      </p>

                    </div>

                    <Link
                      to="/detection"
                      className="w-full px-6 py-3 bg-green-500 text-white rounded-xl font-semibold hover:bg-green-600 transition-all text-center"
                    >
                      Upload Leaf Image
                    </Link>

                  </div>

                </div>

              </div>

            </div>

          </motion.div>

        </div>

      </div>
    );
  }

  return (
    <div className="min-h-screen py-12 bg-gradient-to-br from-green-50 via-emerald-50 to-white">

      <div className="container mx-auto px-4">

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-4xl mx-auto"
        >

          <div className="flex items-center justify-between mb-6">

            <button
              onClick={() => navigate(-1)}
              className="flex items-center space-x-2 text-green-600 hover:text-green-700"
            >
              <FaArrowLeft />

              <span>
                Back
              </span>

            </button>

            <div className="flex items-center space-x-3">

              <button
                onClick={handleShare}
                className="p-2 text-gray-500 hover:text-green-600 transition-colors"
                title="Share"
              >
                <FaShareAlt />
              </button>

              <button
                onClick={handleDownload}
                className="p-2 text-gray-500 hover:text-green-600 transition-colors"
                title="Download"
              >
                <FaDownload />
              </button>

            </div>

          </div>

          <div className="bg-white rounded-3xl shadow-lg overflow-hidden">

            <div className="bg-gradient-to-r from-green-500 to-emerald-600 p-8 text-white">

              <div className="flex items-center justify-between">

                <div>

                  <h1 className="text-3xl font-bold">
                    Prediction Result
                  </h1>

                  <p className="text-green-100 mt-1">
                    Analysis complete for your plant leaf
                  </p>

                </div>

                <div className="text-center">

                  <div className="text-5xl font-bold">
                    {confidence.toFixed(2)}%
                  </div>

                  <div className="text-sm text-green-100">
                    Confidence
                  </div>

                </div>

              </div>

            </div>

            <div className="p-8">

              <div className="grid grid-cols-1 md:grid-cols-3 gap-8">

                <div className="md:col-span-1">

                  {preview ? (

                    <div className="bg-gray-50 rounded-2xl p-4">

                      <img
                        src={preview}
                        alt="Uploaded leaf"
                        className="w-full max-h-72 object-contain rounded-xl"
                      />

                      <p className="text-xs text-gray-500 text-center mt-3 break-all">
                        {filename}
                      </p>

                    </div>

                  ) : (

                    <div className="bg-green-50 rounded-2xl p-8 flex items-center justify-center">
                      <FaLeaf className="text-7xl text-green-500" />
                    </div>

                  )}

                </div>

                <div className="md:col-span-2">

                  <div className="mb-6">

                    <div className="flex items-center space-x-4 flex-wrap gap-2">

                      <div
                        className={`px-4 py-2 rounded-xl font-semibold ${
                          isHealthy
                            ? 'bg-green-100 text-green-600'
                            : 'bg-red-100 text-red-600'
                        }`}
                      >

                        {isHealthy ? (

                          <FaCheckCircle className="inline mr-2" />

                        ) : (

                          <FaExclamationTriangle className="inline mr-2" />

                        )}

                        {status}

                      </div>

                      <div className="text-sm text-gray-500">
                        Detected: {formattedDisease}
                      </div>

                    </div>

                    <div className="mt-3">

                      <span className="text-gray-600">
                        Plant:
                      </span>

                      <span className="font-semibold text-gray-900 ml-2">
                        {plantName}
                      </span>

                    </div>

                  </div>

                  <div className="mb-6">

                    <h3 className="text-lg font-bold text-gray-900 mb-3">
                      Prediction Details
                    </h3>

                    <div className="bg-gray-50 rounded-2xl p-5">

                      <div className="flex justify-between items-center mb-3">

                        <span className="text-gray-600">
                          Confidence
                        </span>

                        <span className="font-bold text-green-600">
                          {confidence.toFixed(2)}%
                        </span>

                      </div>

                      <div className="w-full bg-gray-200 rounded-full h-3">

                        <div
                          className="bg-green-500 h-3 rounded-full transition-all"
                          style={{
                            width: `${Math.min(
                              confidence,
                              100
                            )}%`
                          }}
                        />

                      </div>

                    </div>

                  </div>

                  <div className="mb-6">

                    <h3 className="text-lg font-bold text-gray-900 mb-2">
                      Detected Condition
                    </h3>

                    <p className="text-gray-600">
                      The DeepLeaf VGG19 model identified this image as:
                    </p>

                    <p className="text-xl font-bold text-green-600 mt-2">
                      {formattedDisease}
                    </p>

                  </div>

                  <div className="mt-8 flex gap-4">

                    <Link
                      to="/remedies"
                      className="flex-1 px-6 py-3 bg-green-500 text-white rounded-xl font-semibold hover:bg-green-600 transition-all text-center"
                    >
                      View Remedies
                    </Link>

                    <Link
                      to="/detection"
                      className="flex-1 px-6 py-3 border-2 border-green-500 text-green-600 rounded-xl font-semibold hover:bg-green-50 transition-all text-center"
                    >
                      New Detection
                    </Link>

                  </div>

                </div>

              </div>

            </div>

          </div>

        </motion.div>

      </div>

    </div>
  );
};

export default PredictionResult;